### ISSUE TITLE
mcclim-regression: CORE:&VA-REST fell through ECASE expression.

### ISSUE THREAD

**Issue by kpoeck** [clasp-developers/clasp#1127]
compiling a file with the following content, i get:
```lisp
(in-package :cl-user)

(defclass standard-application-frame ()())

(defvar *input-buffer*)

(defun frame-event-queue (frame)
  frame)

(defun frame-input-buffer (frame)
  frame)

(defmethod make-pane-1 :around (fm (frame standard-application-frame) type
                                &rest args
                                &key (event-queue nil evq-p) &allow-other-keys)
  ;; Default event-queue to the frame event queue.
  (declare (ignore event-queue))
  (if (null evq-p)
      (let ((evq (frame-event-queue frame))
            (*input-buffer* (frame-input-buffer frame)))
        (apply #'call-next-method fm frame type :event-queue evq args))
      (call-next-method)))
````
in slime I get - with the serial compiler to simplify:
```lisp
CORE:&VA-REST fell through ECASE expression.
Wanted one of (:REQUIRED &OPTIONAL &KEY &REST &ALLOW-OTHER-KEYS).
   [Condition of type CORE:CASE-FAILURE]
````
the error is from here:
```lisp
(in-package #:cleavir-bir-transformations)

(defun check-argument-list-compatible (arguments function)
  (let ((lambda-list (cleavir-bir:lambda-list function))
        (nsupplied (length arguments))
        (nrequired 0)
        (noptional 0)
        (restp nil))
    (cleavir-bir:map-lambda-list
     (lambda (state item index)
       (declare (ignore item index))
       (ecase state
         (:required (incf nrequired))
         (&optional (incf noptional))
         ((&rest &key) (setf restp t))
         (&allow-other-keys)))
     lambda-list)
    (let ((nfixed (+ nrequired noptional)))
      (if (and (<= nrequired nsupplied) (or restp (<= nsupplied nfixed)))
          t
          (warn "~a is passed ~d arguments, but expects ~@?"
                (cleavir-bir:name function) nsupplied
                (cond (restp "at least ~d")
                      ((zerop noptional) "exactly ~d")
                      ((zerop nrequired) "at most ~*~d")
                      (t "between ~d and ~d"))
                nrequired nfixed)))))
````

**Comment by kpoeck** [comment]
This is a potential-fix, allows me to compile mcclim. Whether this is the right thing t do, Bike and Karlosz will know better:
```lisp
(in-package #:cleavir-bir-transformations)

(defun check-argument-list-compatible (arguments function)
  (let ((lambda-list (cleavir-bir:lambda-list function))
        (nsupplied (length arguments))
        (nrequired 0)
        (noptional 0)
        (restp nil))
    (cleavir-bir:map-lambda-list
     (lambda (state item index)
       (declare (ignore item index))
       (ecase state
         (:required (incf nrequired))
         (&optional (incf noptional))
         ((&rest &key) (setf restp t))
         ((&allow-other-keys #+clasp core:&va-rest))))
     lambda-list)
    (let ((nfixed (+ nrequired noptional)))
      (if (and (<= nrequired nsupplied) (or restp (<= nsupplied nfixed)))
          t
          (warn "~a is passed ~d arguments, but expects ~@?"
                (cleavir-bir:name function) nsupplied
                (cond (restp "at least ~d")
                      ((zerop noptional) "exactly ~d")
                      ((zerop nrequired) "at most ~*~d")
                      (t "between ~d and ~d"))
                nrequired nfixed)))))
````

**Comment by Bike** [comment]
let me elaborate on what's happening here for future reference.

Clasp has a nonstandard lambda list keyword, `&va-rest`, to indicate a `&rest` parameter that doesn't need to actually be a list, which can make things a little bit faster. We use it in only a few places. One of those places is the definition of `call-next-method`; however we only actually generate a `call-next-method` function if we really have to, so it doesn't usually come up.

In the `make-pane-1` defmethod, `call-next-method` is used directly in a call form `(call-next-method)` and also as a function object passed to `apply`. Because of the latter, a `call-next-method` function is actually generated. However, Cleavir tries to inline it in the `(call-next-method)` form. To do so, it tries to check whether the arguments of the call are valid given the function's lambda list. But it doesn't know about `&va-rest` so problems happen.

Some solutions here:

1. Make Cleavir abort more gracefully if it runs into a problem during an optimization pass like this. We should do this just for the sake of robustness. We'd probably reduce the error to a warning or something, so the code would compile but print an idiotic warning, so this doesn't completely solve the problem.
2. Have Cleavir handle `&va-rest`, as in this patch. I'd really prefer not to do this for cleanliness reasons, and because it doesn't solve the problem for Cleavir, if other implementations have their own custom lambda list keywords.
3. Remove `&va-rest` from Clasp, or at least from `call-next-method`. Doable. Doesn't completely solve the problem, but in practice we don't have other functions with `&va-rest` so it would probably work ok.
4. Generalize Cleavir. Would take some thought, but it's probably the best solution.

i can do 3 pretty easily and 1 as well, so I'll probably focus on that

**Comment by Bike** [comment]
Incidentally, this leads to a simpler reproduction: Just compile the somewhat nonsensical code

```
(defmethod foo (x)
  (if x (apply #'call-next-method x) (call-next-method)))
```

**Comment by Bike** [comment]
1 turned out to be harder than I thought. But, I tried removing `&va-rest` from `call-next-method` and now my example works and mcclim loading gets stuck on some other problem. I could push that

**Comment by Bike** [comment]
Not a perfect solution, but https://github.com/s-expressionists/Cleavir/commit/8843a56f7f715e1b9be27f09d9a94a3fe813068f fixes this, I think.

**Comment by kpoeck** [comment]
mcclim seems to work fine for me, but I might have patched something I don't remember. If you create an issue for the problem you observed while compiling mcclim, I could have a look.
