### ISSUE TITLE
(multiple-value-prog1 (values-list nil)) -> segmentation violation

### ISSUE THREAD

**Issue by kpoeck** [clasp-developers/clasp#1215]
`(multiple-value-prog1 (values-list nil))`
-> 
Condition of type: SEGMENTATION-VIOLATION
#<TYPE-ERROR signaled while printing condition>
No restarts available.

So obviously there is another error printing the condition.

I printed the address in handle_segv and it is e.g. `00007ffee7abbff8`

**Comment by Bike** [comment]
The problem appears to occur while constant folding the `values-list` call. The `multiple-value-prog1` isn't actually required, but it does need to be `(values-list nil)` rather than some longer constant list.

**Comment by Bike** [comment]
ok, yeah, it's a runtime problem. `(multiple-value-call #'values (values-list nil))` => crash

**Comment by Bike** [comment]
The problem can be demonstrated without constant folding with the function `(lambda (L) (multiple-value-call #'values t (values-list L)))`, or equivalently `(lambda (L) (multiple-value-call #'values t (apply #'values L)))`. There is only a problem if L is an empty list; with more elements it's fine. The T is also needed, probably so that m-v-c actually needs to paste. I think values-collect may be a bit broken.
