### ISSUE TITLE
Bug affecting random-state library

### ISSUE THREAD

**Issue by phantomics** [clasp-developers/clasp#1248]
This bug affects Shinmera's random-state library (https://github.com/Shinmera/random-state/). With the package loaded, try:

```lisp
(random-state:random-int (random-state:make-generator :mersenne-twister-64) 0 3)
```
The 0 and 3 are arbitrary, it fails with all pairs of integers I've tried.

**Comment by Bike** [comment]
When you report a bug, please be specific about what behavior you see and what behavior you'd expect. "fails" can mean a lot of things in different contexts, and in general we're not going to be familiar with what every library is expected to do.

In this case I'm guessing that what you expected was an integer from 0 to 3, and what you got was an error `Array index 312 is out of bounds (integer 0 (312)) on axis 0.`

**Comment by Bike** [comment]
I believe this is due to a small bit of nonconforming code in random state. I filed a PR here: Shinmera/random-state#11

That said, if we're going to compile a technically-incorrect loop with different semantics, we should be signaling a warning and not just a style warning, so as to get an early failure. I'll do that. ...though if it breaks too many libraries, i'll have to think of something else.

**Comment by Shinmera** [comment]
"breaks too many libraries" -- wouldn't it just indicate a lot of libraries that are now already silently broken?

**Comment by Bike** [comment]
Yes, but it could still be an issue for Clasp practically speaking, at least until said libraries are fixed.

**Comment by phantomics** [comment]
It works now, thanks Bike and Shinmera for the fix.
