### ISSUE TITLE
ansi-regressions with floats

### ISSUE THREAD

**Issue by kpoeck** [clasp-developers/clasp#1251]
**Describe the bug**
floating-point-tests in ansi-suite fail.
can be reduced to:
````
COMMON-LISP-USER> (let ((x nil))
  (setq x (- (FLOAT (FLOAT-RADIX 1.0) 1.0))))

Condition of type: TYPE-ERROR
NIL is not of type SINGLE-FLOAT.
Available restarts:
(use :r1 to invoke restart 1, etc.)

1. (RESTART-TOPLEVEL) Go back to Top-Level REPL.
````
**Expected behavior**
````
(let ((x nil))
  (setq x (- (FLOAT (FLOAT-RADIX 1.0) 1.0))))
-2.0
````

**Context**
commit 76aa6b16feb20c855e6d70490bde2fdf60088ee8 (HEAD -> main, upstream/main)
macos 12.1
COMMON-LISP-USER> (clasp-cltl2:declaration-information 'optimize)
((COMPILATION-SPEED 1) (DEBUG 1) (SPACE 1) (SPEED 1) (SAFETY 1))

**Comment by Bike** [comment]
Representation selection incorrectly takes whatever vrtype (representation) among writers of a variable it happens to see last, rather than the maximum. The binder puts in vrtype `:object` and the setq puts in vrtype `:single-float`. The variable is selected as having rtype `(:single-float)`, so a cast is put in from NIL to `single-float`, which fails.

**Comment by Bike** [comment]
Ideally a pass would just eliminate the first write since it's never actually used, but unfortunately we're not that sophisticated about control flow and reaching definitions at the moment.

**Comment by Bike** [comment]
This example is fixed for me after aa894f3.

**Comment by kpoeck** [comment]
that fixed 75 ansi failures

**Comment by Bike** [comment]
jesus
