### ISSUE TITLE
ansi-tests Bit for bit arrays with fill pointer fails

### ISSUE THREAD

**Issue by kpoeck** [clasp-developers/clasp#1253]
**Describe the bug**
`(bit (make-array 2 :element-type 'bit :initial-element 1 :fill-pointer 1) 1) errors`

**Expected behavior**
the expression returns 1

**Actual behavior**
`TYPE-ERROR #*1 is not of type (NOT CORE:BIT-VECTOR-NS).`

**Code at issue**

```lisp
(bit (make-array 2 :element-type 'bit :initial-element 1 :fill-pointer 1) 1)

Condition of type: TYPE-ERROR
#*1 is not of type (NOT CORE:BIT-VECTOR-NS).
Available restarts:
(use :r1 to invoke restart 1, etc.)

1. (RESTART-TOPLEVEL) Go back to Top-Level REPL.


(LAMBDA (&OPTIONAL CLASP-CLEAVIR::V &REST CLASP-CLEAVIR::IGN))
```

If the code is more than a few dozen lines, please attach a source file instead.

**Context**
````
(values
 (CORE:CLASP-GIT-FULL-COMMIT)
 (software-version)
 (software-type)
 (machine-type)
 (machine-version))

"76aa6b16feb20c855e6d70490bde2fdf60088ee8"
"0.4.4-1193-g76aa6b16f"
"Darwin"
"x86_64"
"Darwin Kernel Version 21.2.0: Sun Nov 28 20:28:54 PST 2021; root:xnu-8019.61.5~1/RELEASE_X86_64"
````

**Comment by Bike** [comment]
https://github.com/clasp-developers/clasp/blob/main/src/lisp/kernel/lsp/arraylib.lsp#L161-L169 I suspect the declaration on L165 could cause this. It's definitely incorrect, so let me just edit that out, though I won't be able to test today

**Comment by Bike** [comment]
Still doesn't work with it. Further investigation revealed that subtypep is once again broken on some array types: `(subtypep '(array * *) '(not core:bit-vector-ns))`. I suspect the type system thinks `core:bit-vector-ns` is bottom or near bottom for some reason, which would cause all kind of screwups.

**Comment by Bike** [comment]
Here's what I think is happening. Say we have `(lambda (a) (declare ((array bit) a)) (typep a '(array bit)))`. The `typep` expands into a bunch of `typeq` conditionals, one of which is `(if (typeq a core:mdarray-bit) t nil)`. Since `a` has been declared to be a bit array, and `(array bit)` is understood to be a subtype of `core:mdarray-bit` (specifically, they are the same type), Cleavir after my recent changes converts this typeq into a type check - `(if (typeq a core:mdarray-bit) t (error ...))` basically - and then moves this check up. However, array types are screwy, and `(typeq a core:mdarray-bit)` is actually false of bit vectors and stuff.

This is the umpteenth problem I've hit with array types. I think I need to go in and do something to the actual runtime class hierarchy to make this less ridiculous.
