### ISSUE TITLE
caught ERROR: #<LLVM-SYS:VALUE> is not of type INTEGER.

### ISSUE THREAD

**Issue by bohonghuang** [clasp-developers/clasp#1376]
**Code at issue**

```lisp
(locally (declare (optimize (debug 3)))
           (let* ((a (- 0.5 (* 0.5 (cos (/ (* 0 pi) 256))))))
             (setf a (- 1.0 a))
             (loop :for i :below 1 :do (print a))))
```

**Actual behavior**
The compiler prints: 
```
; compilation unit finished
;   caught 1 ERROR condition
;                               
; caught ERROR:
;   #<LLVM-SYS:VALUE> is not of type INTEGER.
;     at /tmp/temp.lisp 1:0
```

**Expected behavior**
With `(optimize (debug 2))` declaration, it successfully outputs: 

```
1.0d0
```
**Context**
* Clasp Version: 2.0.0
* Operating System: Manjaro Linux x86_64 (Kernel: 5.15.74-3-MANJARO)

**Comment by Bike** [comment]
this is happening because at debug 3 we dump a lot of forms for the stepper, and in this case a form is a literal 0 and the stepping code doesn't expect an immediate. Testing a fix now. This probably indicates a deeper flaw in constant folding, since this ought to compile down to `(loop for i below 1 do (print 1d0))` at least.
