### ISSUE TITLE
Questions about shared libraries and cross-compiling

### ISSUE THREAD

**Issue by phantomcraft** [clasp-developers/clasp#1378]
Can CLASP be used to build dynamic/shared libraries through LLVM?

And about cross-compiling, can CLASP emit .bc (LLVM IR bitcode) files for further compiling with LLVM and produce either multi-platform and cross-platform executables?

PS: Sorry, I'm not an experienced programmer, what I do currently is just scripts in Python (but I want to study Common Lisp deeply).

**Comment by phantomcraft** [comment]
There is no way to get rid of bug label, I ask to replace with "question" label.

**Comment by Bike** [comment]
Building shared libraries would be difficult because Clasp has a very big runtime and we're not really geared for separating things out.

We can certainly emit LLVM bitcode, though. If you use the serial compiler (`cmp:compile-file-serial`) it will write out a .bc file you can use.

Because we use LLVM as our backend, we are in theory able to compile for any target LLVM supports. However in Clasp itself we also use several other LLVM features that are not as broadly supported, especially JIT compilation. We just added an alternate non-LLVM compiler that may make it easier to run on systems without that extra support, but we haven't tried that yet.

**Comment by phantomcraft** [comment]
Ok, thanks for the reply, you said it would be difficult, but I'm still interested on Clasp.

**Comment by phantomcraft** [comment]
@Bike 

> Building shared libraries would be difficult because Clasp has a very big runtime and we're not really geared for separating things out.

Do you mean that Clasp is very complex to find the components and (maybe?) module to use inside the LISP code?

**Comment by Bike** [comment]
Mostly I mean that the Clasp runtime is huge and not decomposable, so your shared library would be really big.

**Comment by phantomcraft** [comment]
@Bike 

Do you have an idea on how many MegaBytes a simple library made with Clasp would be?

**Comment by Bike** [comment]
At least several hundred.

**Comment by phantomcraft** [comment]
o_0

**Comment by Bike** [comment]
It's not unused code. (And we do do dead code elimination.) It's the entire system, including for example the several hundred functions in the standard library.
