### ISSUE TITLE
Disassembling returns "There were no associated functions available for disassembly"

### ISSUE THREAD

**Issue by GOFAI** [clasp-developers/clasp#181]
The example of disassembling a function given by [this year-old blog post](https://drmeister.wordpress.com/2014/09/30/things-you-can-do-with-clasp-1/) doesn't return LLVM-IR code, instead merely a statement that "There were no associated functions available for disassembly":

``` lisp
>> (defun add (x y) (+ x y))

ADD
>> (add 3 5)

8
>> (disassemble 'add)
Disassembling function: #<COMMON-LISP:COMPILED-FUNCTION ADD CompiledClosure>
There were no associated functions available for disassembly
```

**Comment by drmeister** [comment]
This is a long-standing issue that I fix and break and fix and break. (sigh)
Mostly because I had multiple places binding the list of llvm::Function objects generated by a compile to the Closure that was generated and they were undoing the work I was doing when I was binding them correctly.  I tracked down all of the places and deleted the code.  
Now it work like this: (see compile-in-env in compiler.lsp)
(let ((cmp:*associated-functions-for-one-compile* nil))
    (let ((closure <compile a form, generating multiple llvm::Function objects that are pushed into *associated-functions-for-one-compile*>))
    (core:set-associated-functions closure cmp:*associated-functions-for-one-compile*)))

**Comment by Bike** [comment]
Working again.
