### ISSUE TITLE
Implement better source-location tracking 

### ISSUE THREAD

**Issue by drmeister** [clasp-developers/clasp#288]
stassats suggested this:

```
(defvar *list-reader* (get-macro-character #\( nil))

(defvar *forms* (make-hash-table :test #'eq))

(set-macro-character #\(
                     (lambda (stream char)
                       (let ((start (file-position stream))
                             (result (funcall *list-reader* stream char)))
                         (setf (gethash result *forms*) start)
                         result)))

(eval-when (:compile-toplevel :execute :load-toplevel)
  (defparameter *form-stack* nil))

(defmacro source-location ()
  (format t "Source location: ~a~%" (loop for form in *form-stack*
                                       when (gethash form *forms*)
                                       return it))
  nil)

(defmethod cleavir-generate-ast::convert-form :around (form info env system)
  (push form *form-stack*)
  (unwind-protect
       (call-next-method)
    (pop *form-stack*)))

(progn (defun foo ()
         (source-location)))
```

**Comment by drmeister** [comment]
I've added and uncommented code that has the same effect as above.  Clasp does things a little differently because it uses a weak-key-hash-table for *forms* and rather than change the #\( reader macro it maps CONSes to source locations in the C++ Common Lisp reader.  Also Clasp defines a SourcePosInfo_O object, which keeps track of file name and file offset info.

**Comment by Shinmera** [comment]
How would I go about testing this?

**Comment by Bike** [comment]
Most of the above is obsolete now.

OK so. Organizationally everything is a mess as usual. We have multiple structures for dealing with source locations:

- SourceFileInfo_O in sourceFileInfo.h handles just files. There's a registry that maps integers to these things forsome reason.
- SourcePosInfo_O in the same file includes the integer index for a SourceFileInfo_O, and also an offset and line number and stuff. It's basically what we want.
- `source-location` in source-location.lsp is, however, what we actually export and what the swank backend uses presently. It has a pathname (not just the integer) and an offset, but drops the line and column.
- We additionally throw around just the values (file integer, lineno, column, offset) sometimes.

Obviously this is all kind of dumb. I think SourcePosInfo_O has all the information we need and we should standardize on that, ideally with an actual pathname instead of a weird integer key though.

However there is a bootstrap issue. We can't really dump literal SourcePosInfo's even though we would like to, because although SourcePosInfo is a C++ thing and thus available always, `make-load-form` is established pretty late. Even to give classes source positions (e1f3af8) I had to rearrange CLOS boot. For stuff that's defined way earlier like `defvar` it's kind of a crapshoot.

In more detail, say we had `(defvar *foo* 17)` expand into `(progn (other-defvar-stuff) (setf (variable-source-location '*foo*) #<CURRENT SOURCE POS>))`. The compiler would balk whenever we `defvar`d before `make-load-form` was in place.

Pretty much every option for improvement is some kind of hack:

- Fix boot. Not a hack but also probably not going to happen.
- Change the literal compiler to deal with SourcePosInfo specially instead of going through `make-load-form`.
- Have `defvar` and co. expand into code that makes the SourcePosInfo, e.g. `(load-time-value (core:make-cxx-object ...))`. This would work but entails the `make-load-form` definition kind of being repeated everywhere, or possibly once early on along with an extractor function for the macros.
- Use the source info from associated functions. This only works for those that _have_ an associated function, such as type definitions.

Right now I'm going to go with the latter because it mostly doesn't require altering old code.

**Comment by Bike** [comment]
Variables have source locations now. It's kind of a crappy boot workaround.

**Comment by Bike** [comment]
closing this since almost everything is covered
