### ISSUE TITLE
Upstream ASDF doesn't work with clasp

### ISSUE THREAD

**Issue by drmeister** [clasp-developers/clasp#295]
Pipping said the following:
- No function that spawns processes asynchronously. vfork_execvp is slightly more flexible than system but not a lot. So %run-program cannot be implemented.
  Regular test suite fails 15/60 tests
- feature :common-lisp not defined (can be worked around)
- read-sequence return value incorrect: https://github.com/drmeister/clasp/issues/294

Functions not implemented:
- delete-package
- open-stream-p
- unexport

**Comment by drmeister** [comment]
I'm adding unexport, delete-package and open-stream-p

**Comment by drmeister** [comment]
I've implemented unexport, delete-package and open-stream-p.
I've also fixed read-sequence.
I've added :common-lisp to *features*

**Comment by drmeister** [comment]
I pushed the changes to testing

**Comment by drmeister** [comment]
All that's missing is a function to spawn processes asynchronously.  What would that involve?

**Comment by pipping** [comment]
This is the complete test log for revision d698c35: https://gist.github.com/pipping/dacec76fcc2d6d2b33878e6efdc380ff

There are a few issues that will be more difficult to debug than the ones I've mentioned earlier simply because it's not immediately clear from the log what the problem is. These include:
The assertion (NOT (ASDF/SYSTEM:FIND-SYSTEM "test-asdf/force1" NIL)) failed

The assertion (HANDLER-CASE (LET ((UIOP/LISP-BUILD:*COMPILE-FILE-FAILURE-BEHAVIOUR* :ERROR)) (ASDF/OPERATE:LOAD-SYSTEM 'ASDF-TEST::TEST-COMPILE-FILE-FAILURE :FORCE T) NIL) (UIOP/LISP-BUILD:COMPILE-FILE-ERROR NIL T)) failed

The assertion (UIOP/PATHNAME:LOGICAL-PATHNAME-P (ASDF/COMPONENT:COMPONENT-PATHNAME ASDF-TEST::SYS)) failed

The assertion (NOT (ASDF/SYSTEM:FIND-SYSTEM "test-asdf/force1" NIL)) failed

**Comment by pipping** [comment]
New log, for revision 3533831: https://gist.github.com/pipping/d9b9b8509c1bfd7a15a2929bcb5e74e5

**Comment by kpoeck** [comment]
works even with asdf 3.3.3
