### ISSUE TITLE
to few arguments passed to a method gives confusing error message

### ISSUE THREAD

**Issue by kpoeck** [clasp-developers/clasp#571]
```lisp
COMMON-LISP-USER> (defmethod foo (a b)(list a b))
#<STANDARD-METHOD FOO (T T)>
COMMON-LISP-USER> (foo 1)
Condition of type: SIMPLE-TYPE-ERROR
In function SUBSEQ, the value of an argument is
  2
which is not of the expected type (INTEGER 0 1)
Available restarts:
(use :r1 to invoke restart 1)
````

**Comment by kpoeck** [comment]
but too much arguments is nicely caught
```lisp
COMMON-LISP-USER> (foo 1 2 3)
Condition of type: SIMPLE-PROGRAM-ERROR
Too many arguments when calling (METHOD FOO (T T)) - you provided 3 and 2 are allowed
Available restarts:
(use :r1 to invoke restart 1)
1. (RESTART-TOPLEVEL) Go back to Top-Level REPL.
````

**Comment by Bike** [comment]
I believe this is caused by the `(subseq argument-classes 0 key-length)` in `do-dispatch-miss` in closfastgf. If on the other hand there are too _many_ arguments, they'll just get truncated there, and there will be a too-many-arguments error only when the method function is actually called.

This is similar to #516. We might have to rethink some things... I can fix this in the short term, though.

**Comment by Bike** [comment]
I've fixed this somewhat, except that after the first (memoizing) call, it will report a function name of LAMBDA^junkgoeshere

**Comment by kpoeck** [comment]
Fixed as you said, nice
