### ISSUE TITLE
(- most-negative-fixnum) -> -2305843009213693952

### ISSUE THREAD

**Issue by kpoeck** [clasp-developers/clasp#579]
should be 2305843009213693952

**Comment by kpoeck** [comment]
there is a compile macro calling core:negate, but is not obvious what is called later

**Comment by Bike** [comment]
"later"?

Anyway, `(core:negate most-negative-fixnum)` returns this as well, as does an uncompilermacroed `(- most-negative-fixnum)`. The former is the important one, because the `-` function will call `negate` if there are no more arguments.

`clasp_negate` tries to return a fixnum if given a fixnum, but that doesn't work for `most-negative-fixnum`. That's probably the issue.
