### ISSUE TITLE
The reader interprets 1.e-7 as a symbol.

### ISSUE THREAD

**Issue by drmeister** [clasp-developers/clasp#678]
Just that - I hit this while trying to build sucle.

**Comment by Bike** [comment]
1.e7 is misread, but 1e7 is properly read as a number.

**Comment by Bike** [comment]
Looking at `interpret_token_or_throw_reader_error`. When reading 1.e7, it will start in state tstart, then read a digit and go to tintt, then read the radix point and go to tintp. The tintp state goes to the tfloat0 state if it finds a digit, but otherwise to sym. i think it needs to test the exponent

**Comment by Bike** [comment]
The reason I didn't try that right off is because it looked like that would make the tintp and tfloat0 states identical and I'm just wondering if it won't screw something else up.

**Comment by kpoeck** [comment]
This is fixed with drmeisters coomit, here a test case (will make pr)
(test issue-678
      (floatp (first (list 1.e-7))))
