### ISSUE TITLE
(ql:quickload :cl-jpeg) does not work with (setq clasp-cleavir::*use-ast-interpreter* t)

### ISSUE THREAD

**Issue by kpoeck** [clasp-developers/clasp#727]
Aborted 1 hour after Performing compile-time optimization.. please wait.
with `(setq clasp-cleavir::*use-ast-interpreter* nil)` compilation works fine

**Comment by Bike** [comment]
Based on a backtrace in IRC, this is because of my apparently foolish assumption that nobody would want to evaluate a defcallback at compile time. The AST interpreter cannot handle defcallback ([and a few other special operators](https://github.com/clasp-developers/clasp/blob/master/src/lisp/kernel/cleavir/ast-interpreter.lisp#L392-L394)) in any sane way. I'll put something in to fall back to the compiler if the interpreter is inadequate.

**Comment by Bike** [comment]
I've pushed df191d3 and 87d1209, which let the AST interpreter fall back to using the compiler. However I'm still seeing compile-time `defcallback` causing issues due to runtime values being used instead of the compile-file version... I haven't tried cl-jpeg specifically though.

**Comment by kpoeck** [comment]
This specific error does not happen anymore, will report other problems with cl-jpeg in separate issues
