### ISSUE TITLE
cst regression: adjoin does not error with test with 1 or 3 arguments

### ISSUE THREAD

**Issue by kpoeck** [clasp-developers/clasp#782]
```lisp
(let () (ADJOIN 'C '(a 1) :TEST #'IDENTITY))
=> (A 1)
(let () (adjoin 'c '(a 1) :test #'(lambda (a b c))))
=> (C A 1)
but 
(adjoin 'c '(a 1) :test #'(lambda (a) nil))

Condition of type: SIMPLE-PROGRAM-ERROR
Too many arguments for LAMBDA^COMMON-LISP^FN^^ - got 2 and expected 1

Available restarts:
(use :r1 to invoke restart 1)
1. (RESTART-TOPLEVEL) Go back to Top-Level REPL.
````
all that works fine in ast

**Comment by Bike** [comment]
Here's what's happening here. As you've noted with the `(let () ...)`, this is a problem with compiled `adjoin` calls, not the function itself. The compiler macro on `adjoin` expands your first example into e.g.

```
(LET ((#:%VALUE13767 'C) (#:%LIST13771 '(A 1)))
  (LET ((#:%VALUE-AFTER-KEY-FUNCTION-13772 #:%VALUE13767))
    (COMPILER::DO-IN-LIST
     (#:%ELT13769 #:%SUBLIST13768 #:%LIST13771
      (CONS #:%VALUE13767 #:%LIST13771))
     (WHEN (IDENTITY #:%VALUE-AFTER-KEY-FUNCTION-13772 #:%ELT13769)
       (RETURN #:%LIST13771)))))
```

The problem is indicated by `(IDENTITY #:%VALUE-AFTER-KEY-FUNCTION-13772 #:%ELT13769)`. The reason this does not signal an error is the same as in #777 - the underlying Cleavir issue that inlined functions (such as `identity`) don't check for proper argument counts, https://github.com/robert-strandh/SICL/issues/137
