### ISSUE TITLE
Ansi-tests regression: (let ()(make-instance)) -> UNIX-SIGNAL-RECEIVED

### ISSUE THREAD

**Issue by kpoeck** [clasp-developers/clasp#820]
```lisp
COMMON-LISP-USER> (let ()(make-instance))
; caught WARNING:
;   ERROR during compiler-macro-expansion:
;     Too few arguments supplied to a macro or a destructuring-bind form:
;     (MAKE-INSTANCE)
;   (Using original form instead.)
; 
; compilation unit finished
;   caught 1 WARNING condition

Condition of type: UNIX-SIGNAL-RECEIVED
Serious signal 11 caught.
````

**Comment by kpoeck** [comment]
The warning is obviously totally correct, the form should rather generate a program-error in safe code

**Comment by Bike** [comment]
If that warning is being signaled, it's going to leave in a regular call instead. The unix signal seems to be a segfault from the discriminating function interpreter, which is called as part of calling `make-instance`. If you do `(let () (declare (notinline make-instance)) (make-instance))`, you still get the `unix-signal-received`.

If you do it _twice_ the system seems to hang. That's pretty bad.

**Comment by Bike** [comment]
Brief trip to lldb suggests it's a segfault both times, but for some reason we don't get a lisp signal the second time. That's probably a different problem, in the signal handling. So the discriminating function interpreter not handling insufficient arguments correctly is probably what we can solve here.

**Comment by Bike** [comment]
Doesn't happen with `(apply #'make-instance nil)` or `(funcall #'make-instance)`, as far as I can tell. I'm a bit mystified.

**Comment by kpoeck** [comment]
Is the a difference between 
(let () (declare (notinline make-instance)) (make-instance)) and
(make-instance) or (apply #'make-instance nil) or (funcall #'make-instance)
?

**Comment by Bike** [comment]
Well, entering `(make-instance)` by itself in the REPL won't invoke the compiler, it'll just do a funcall. the apply will call the apply function. `(funcall #'make-instance)` in the repl will just call funcall, and if compiled it will also result in a call to funcall because the compiler macro fails.

Might be simpler to just put all this test code in a lambda, like `(lambda () (make-instance))`, in the future, so that we don't need to worry about the repl is doing specially.

**Comment by Bike** [comment]
My comment earlier was wrong - this isn't an issue with the discriminating function interpreter, but rather with the compiler (which we're using for `make-instance` because of satiation). If a discriminating function takes a vaslist argument it doesn't do any argument count check.

I semi-accidentally put in a check in the interpreter - doesn't fix this particular issue. (Also, it needs to have its error message improved.)

**Comment by Bike** [comment]
I think c89e234 has fixed this. The weird signaling thing might still be an issue though.

**Comment by kpoeck** [comment]
fixed!
