### ISSUE TITLE
llvm@9 lisp format no longer works

### ISSUE THREAD

**Issue by kpoeck** [clasp-developers/clasp#902]
```lisp
COMMON-LISP-USER>> (format t "Bar~2%")                 
Could not format Bar~2% NIL
````
Since this is a format string that cl__format in bformat.cc cannot parse (the 2 before the %".

Don't really know, why the real format is no longer called, perhaps the job of define-compiler-macro format ...)?

**Comment by kpoeck** [comment]
Surprisingly
```lisp
COMMON-LISP-USER> (funcall (compiler-macro-function 'format) '(format t "Bar~2%") nil)
(LET ((STREAM *STANDARD-OUTPUT*))
  (LET ((CORE::ARGS (LIST)))
    (BLOCK NIL
      (WRITE-STRING "Bar" STREAM)
      (LET ((#:G200621 2))
        (DOTIMES (CORE::I #:G200621) (TERPRI STREAM))))))
COMMON-LISP-USER> (let ()(format t "Bar~2%"))
Bar


NIL
````

So the compiler-macro does its job, when its called, is just not called all the time

**Comment by kpoeck** [comment]
This results in hundreds of regressions in the ansi-tests

**Comment by Bike** [comment]
(for any future readers) mostly hashing this out in the irc channel. looks like drmeister removed the lisp redefinition of `cl:format` and doesn't remember why.

And an extra note - a compiler macro could never be adequate for this kind of thing, since the function itself can be passed to higher order functions and so on.

**Comment by kpoeck** [comment]
Yup, my assumption about the compile-macro  was wrong

**Comment by kpoeck** [comment]
fixed
